FROM node:lts-alpine

ENV API_PORT 3000

# Create app directory
WORKDIR /home/node/app
RUN chown -R node:node /home/node/app
USER node

# Transfers the app
COPY . .

# Install dependencies
RUN npm install

# Commands at runtime
CMD [ "npm", "run", "start" ]
